version: "1"

services:
  backend:
    # El build elemento define las opciones de configuración que aplican las implementaciones de Compose para crear una imagen de 
    # Docker desde el origen.
    build:
      # build se puede especificar como una cadena que contiene una ruta al contexto de compilación 
      # o como una estructura detallada:
      # Usando la sintaxis de cadena, solo el contexto de compilación se puede configurar como:

      # Una ruta relativa a la carpeta principal del archivo Compose. Esta ruta DEBE ser un directorio y debe contener unDockerfile
      # services:
      #   webapp:
      #     build: ./dir

      # Una URL del repositorio de git. Las URL de Git aceptan la configuración de contexto en su sección de fragmentos, 
      # separados por dos puntos ( :). La primera parte representa la referencia que Git extrae y puede ser una rama, 
      # una etiqueta o una referencia remota. La segunda parte representa un subdirectorio dentro del repositorio que se usa 
      # como contexto de compilación.
      